[package]
name = "minimal_wgpu_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version="0.19", features=["trace"] }
egui = "0.27"
egui-wgpu = "0.27"
egui-winit = "0.27"
pollster = "0.4.0"
winit = "0.29.15"
